"use strict";
let placeToVisit = ["Turkey", "Pakistan", "America", "England", "Canada"];
console.log(placeToVisit);
console.log(placeToVisit.sort());
console.log(placeToVisit.sort().reverse());
console.log(placeToVisit);
console.log(placeToVisit.reverse());
console.log(placeToVisit.reverse());
let sortedArray = ["Turkey", "Pakistan", "America", "England", "Canada"];
sortedArray.sort();
console.log(sortedArray);
sortedArray.reverse();
console.log(sortedArray);
